# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7b4994806cf28eb7c29da4d7a37a13c7ff95eeb330a871e51545b6c07f7791587d95348e4a4503e4a8a2f715bb94dea2e3e87849403f05e75de34d2354901b

test:
  secret_key_base: d494cfed4134b38ad7bbaf6d96b25f371dcd9dc9ca58b70a7bcd9ec1b5eed0a73c70d616d7538aa12855ee3f309b9b47afb44d26e40dbbe5cec2bf6c3066b7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 057925bd2af84276bb9653f62438f9d959d42d73c3c6d05fbb7386752e0035fd5a3f2c1f12815e7bf6dba0c361280a4c2fd3cb0791574baad9ce807e8f3a7151